# Generated by Django 4.1.2 on 2022-11-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registro_hora_extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.CharField(max_length=100)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Funcionarios.funcionario",
                    ),
                ),
            ],
        ),
    ]
