# Generated by Django 4.1.2 on 2022-11-03 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionarios", "0002_funcionario_departamentos_funcionario_empresa_and_more"),
        ("Registro_hora_extra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registro_hora_extra",
            name="funcionario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="Funcionarios.funcionario",
            ),
            preserve_default=False,
        ),
    ]
